# The routes of the project.
#
# Each route describes how an incoming URL is going
# to be processed by Platform.sh.

"https://stralsund.de/":
    type: upstream
    upstream: "peenelando:http"
    cache:
      enabled: true

      # Base the cache on the session cookie. Ignore all other cookies.
      cookies: ['/^SS?ESS/']

"https://www.stralsund.de/":
    type: redirect
    to: "https://stralsund.de/"
